In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [2]:
response = requests.get("https://agriexchange.apeda.gov.in/IndExp/PortNew.aspx")

In [3]:
response.status_code

200

In [4]:
doc = BeautifulSoup(response.text, "html.parser")

In [8]:
state_list = doc.find_all("select", {"id": "ListBoxState"})

In [10]:
state_option = state_list[0].find_all("option")

In [14]:
states = []
for i in range(1, len(state_option)):
    states.append(state_option[i].text)
states

['Andaman & Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chhattisgarh',
 'Daman & Diu',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu & Kashmir',
 'Karnataka',
 'KERALA',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Odisha',
 'Pondicherry',
 'PUNJAB',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'unspecified',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']

In [5]:
list_element = doc.find_all("select", {"id": "ListBoxProduct"})

In [6]:
option_element = list_element[0].find_all("option")

In [7]:
len(option_element)

44

In [9]:
option_element[0]

In [10]:
products = []
for i in range(1, len(option_element)):
    products.append(option_element[i].text)

In [3]:
years = [
    '1987-88', '1988-89', '1990-91', '1991-92', '1992-93', '1993-94', '1994-95', '1995-96', '1996-97',
    '1997-98', '1998-99', '1999-00', '2000-01', '2001-02', '2002-03', '2003-04', '2004-05', '2005-06', '2006-07',
    '2007-08', '2008-09', '2009-10', '2010-11', '2011-12', '2012-13', '2013-14', '2014-15', '2015-16', '2016-17',
    '2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24 (April-December)'
]

In [2]:
products = ['Floriculture', 'Fruits & Vegetables Seeds', 'Fresh Onions', 'Other Fresh Vegetables', 'Walnuts', 
            'Fresh Mangoes', 'Fresh Grapes', 'Other Fresh Fruits', 'Others (Betel Leaves & Nuts)', 
            'Cucumber and Gherkins( Prepd. &  Presvd)', 'Processed Vegetables', 'Mango Pulp', 
            'Processed Fruits, Juices & Nuts', 'Pulses', 'Buffalo Meat', 'Sheep/Goat Meat', 
            'Other Meat', 'Processed Meat', 'Animal Casings', 'Poultry Products', 'Dairy Products', 'Natural Honey', 
            'Casein', 'Albumin( Eggs & Milk)', 'Groundnuts', 'Guargum', 'Jaggery & Confectionery', 'Cocoa Products', 
            'Cereal Preparations', 'Milled Products', 'Alcoholic Beverages', 'Miscellaneous Preparations', 'Basmati Rice', 
            'Non Basmati Rice', 'Wheat', 'Maize', 'Other Cereals', 'Millet', 'Cashew Kernels', 'Cashewnut Shell Liquid', 
            'Cardanol', 'Prepared Animal Feeder', 'Other Oil Cake/Solid Resdus']

In [12]:
df = pd.read_csv("../../Datasets/Export/Export-Product-Wise/2011-12.csv")

In [13]:
df

,Product Name,Qty(MT),Rs(Crore),% Share(Qty),% Share(Rs)
0,GUARGUM,707326.43,16523.87,3.628,19.984
1,BASMATI RICE,3107280.36,15084.43,15.937,18.243
2,BUFFALO MEAT,987714.46,13757.34,5.066,16.638
3,NON BASMATI RICE,3985294.86,8629.93,20.440,10.437
4,GROUNDNUTS,823500.99,5181.40,4.224,6.266
5,MAIZE,3820554.74,5110.33,19.595,6.180
6,CEREAL PREPARATIONS,301176.67,1887.16,1.545,2.282
7,FRESH ONIONS,1308475.94,1720.57,6.711,2.081
8,ALCOHOLIC BEVERAGES,214097.20,1459.21,1.098,1.765
9,PROCESSED VEGETABLES,223157.97,1236.39,1.145,1.495
10,MISCELLANEOUS PREPARATIONS,229276.62,1218.63,1.176,1.474
11,OTHER FRESH VEGETABLES,663026.41,1148.87,3.401,1.389
12,"PROCESSED FRUITS, JUICES & NUTS",202824.93,1115.08,1.040,1.349
13,PULSES,174554.12,1067.40,0.895,1.291
14,WHEAT,740746.76,1023.27,3.799,1.238
15,JAGGERY & CONFECTIONERY,207686.07,764.17,1.065,0.924
16,CUCUMBER AND GHERKINS( PREPD. & PRESVD),258603.00,745.03,1.326,0.901
17,OTHER FRESH FRUITS,261827.26,714.61,1.343,0.864
18,MANGO PULP,150499.06,620.83,0.772,0.751
19,FRESH GRAPES,94860.03,516.76,0.487,0.625
20,POULTRY PRODUCTS,613381.44,452.68,3.146,0.547
21,FLORICULTURE,30926.02,365.32,0.159,0.442
22,MILLED PRODUCTS,171131.99,358.87,0.878,0.434
23,NATURAL HONEY,25348.90,315.04,0.130,0.381
24,DAIRY PRODUCTS,25632.83,289.30,0.131,0.350
25,FRUITS & VEGETABLES SEEDS,15205.81,287.76,0.078,0.348
26,SHEEP/GOAT MEAT,10085.04,243.62,0.052,0.295
27,WALNUTS,5828.74,230.99,0.030,0.279
28,FRESH MANGOES,63432.96,209.69,0.325,0.254
29,COCOA PRODUCTS,16678.58,175.98,0.086,0.213
30,OTHER CEREALS,45242.66,64.27,0.232,0.078
31,ALBUMIN( Eggs & Milk ),1454.31,53.03,0.007,0.064
32,CASEIN,838.66,37.20,0.004,0.045
33,ANIMAL CASINGS,923.56,27.05,0.005,0.033
34,OTHERS (BETEL LEAVES & NUTS),2472.04,20.09,0.013,0.024
35,Millet,5803.33,18.23,0.030,0.022
36,PROCESSED MEAT,575.94,9.50,0.003,0.011
37,OTHER MEAT,305.97,3.51,0.002,0.004
38,Total,19497752.66,82687.41,100.000,100.000

In [34]:
df[df["Product Name"].str.contains(products[0].upper())].index[0]

21

In [53]:
for i in range(0, len(df) - 1):
    if df["Product Name"].str.contains(products[8].upper(), regex=False)[i] == 1:
        index = i
        break

In [54]:
index

34

In [57]:
df.iloc[index]["Qty(MT)"]

2472.04

In [28]:
data = []
for i in range(0, len(years)):
    internal = []
    index = 0
    df = pd.read_csv(f"../../Datasets/Export/Export-Product-Wise/{years[i]}.csv")

    for j in range(0, len(df) - 1):
        if df["Product Name"].str.contains("FLORICULTURE")[j] == 1:
            index = j
            break

    internal.append(years[i])
    internal.append(df.iloc[index]["Qty(MT)"])
    internal.append(df.iloc[index]["Rs(Crore)"])
    internal.append(df.iloc[index]["% Share(Qty)"])
    internal.append(df.iloc[index]["% Share(Rs)"])
    data.append(internal)

df1 = pd.DataFrame(data, columns=["Year", "Qty(MT)", "Rs(Crore)", "% Share(Qty)", "% Share(Rs)"])
df1.loc[len(df1.index)] = ["Total", df1["Qty(MT)"].sum(), df1["Rs(Crore)"].sum(), 0, 0]
df1.to_csv("../../Datasets/Export/Product-Wise-Time-Series/Floriculture.csv", index=None)

In [15]:
df2 = pd.read_csv("../../Datasets/Export/Export-State-Wise/2017-18.csv")

In [16]:
df2

          State Name      Qty(MT)  Rs(Crore)  % Share(Qty)  % Share(Rs)
0            Gujarat   5703552.23   30115.18        25.457       23.928
1        Maharashtra   4049878.02   25722.97        18.076       20.438
2      Uttar Pradesh   1932019.45   18660.49         8.623       14.827
3            HARYANA    894496.55    8535.63         3.992        6.782
4     Andhra Pradesh   3040272.34    8274.07        13.570        6.574
5         Tamil Nadu   1428493.91    8258.95         6.376        6.562
6        West Bengal   2785375.49    7577.60        12.432        6.021
7             Kerala    275383.97    4407.40         1.229        3.502
8             Punjab    441266.34    3328.72         1.970        2.645
9          Karnataka    215063.98    2783.02         0.960        2.211
10             Delhi    102289.48    1832.52         0.457        1.456
11             Bihar    876293.89    1792.79         3.911        1.424
12         Rajasthan    184332.14    1719.31         0.823        1.366
13         Telangana    131132.63    1283.20         0.585        1.020
14    Madhya Pradesh    143200.33     911.98         0.639        0.725
15            Odisha    101672.10     238.70         0.454        0.190
16               Goa     14632.32     143.83         0.065        0.114
17      Chhattisgarh     52744.00     133.78         0.235        0.106
18       Uttarakhand     17573.50      95.19         0.078        0.076
19             Assam     12616.19      34.37         0.056        0.027
20            Sikkim      2279.84       8.10         0.010        0.006
21           Tripura       208.53       0.15         0.001        0.000
22         Meghalaya        52.00       0.06         0.000        0.000
23  Himachal Pradesh         5.02       0.06         0.000        0.000
24             Total  22404834.25  125858.07       100.000      100.000

In [20]:
data = []
for i in range(20, len(years)):
    internal = []
    index = 0
    df = pd.read_csv(f"../../Datasets/Export/Export-State-Wise/{years[i]}.csv")

    for j in range(0, len(df) - 1):
        if df["State Name"].str.contains("Gujarat")[j] == 1:
            index = j
            break

    internal.append(years[i])
    internal.append(df.iloc[index]["Qty(MT)"])
    internal.append(df.iloc[index]["Rs(Crore)"])
    internal.append(df.iloc[index]["% Share(Qty)"])
    internal.append(df.iloc[index]["% Share(Rs)"])
    data.append(internal)

df1 = pd.DataFrame(data, columns=["Year", "Qty(MT)", "Rs(Crore)", "% Share(Qty)", "% Share(Rs)"])
df1.to_csv("../../Datasets/Export/State-Wise-Time-Series/Gujarat.csv", index=None)